%
% MATLAB commands (clearpath) generated by Rhapsody Control System Designer
% Model Name: Sysmlsimulink
% Simulink Model Name: System
% Generated Date: Sun Jun 03 11:36:14 CST 2018
%
rmpath('C:\研究生课题任务\Simulink')
