%
% MATLAB commands (sim) generated by Rhapsody Control System Designer
% Model Name: Sysmlsimulink
% Simulink Model Name: System
% Generated Date: Sun Jun 03 11:36:14 CST 2018
%
try
	sim('System_Rhap')
catch ME
	msgbox(ME.message, 'Rhapsody - Error', 'error', 'replace')
end
