%
% MATLAB commands (model creation) generated by Rhapsody Control System Designer
% Model Name: Sysmlsimulink
% Structured Simulink Model Name: System
% Generated Date: Sun Jun 03 11:36:14 CST 2018
%
try
	clear all
	bdclose('System_Rhap')
	System_setpath
	new_system('System_Rhap')
	set_param('System_Rhap', 'Description', sprintf(''))
	set_param('System_Rhap', 'StartTime', '0.0')
	set_param('System_Rhap', 'StopTime', '30')
	set_param('System_Rhap', 'InlineParams', 'on')
	set_param('System_Rhap', 'ParameterArgumentNames', '')
	add_block('built-in/ModelReference', 'System_Rhap/itsDriver', 'ModelName', 'sineGenerator', 'Position', [72 104 227 218], 'SimulationMode', 'Normal', 'Description', sprintf(''))
	add_block('built-in/ModelReference', 'System_Rhap/itsMonitor', 'ModelName', 'Scope', 'Position', [377 143 547 257], 'SimulationMode', 'Normal', 'Description', sprintf(''))
	load_system('sineGenerator')
	rhap_oport = ['itsDriver', '/', get_param('sineGenerator/Out1', 'Port')];
	load_system('Scope')
	rhap_iport = ['itsMonitor', '/', get_param('Scope/In1', 'Port')];
	rhap_new_line = add_line('System_Rhap', rhap_oport, rhap_iport, 'autorouting', 'on');
	set_param(rhap_new_line, 'Name', 'itsDriver_Out1')
	clear rhap_oport rhap_iport rhap_new_line
	open_system('System_Rhap')
	save_system('System_Rhap')
	mkdir('success')
catch ME
	msgbox(ME.message, 'Rhapsody - Error', 'error', 'replace')
	mkdir('failure')
end
