######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 14 10:19:05 2012
######################################################################

TEMPLATE = app
TARGET = HelloWorld
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Hello.h MainHelloWorld.h
SOURCES += Hello.cpp MainHelloWorld.cpp
DEFINES += _CRT_SECURE_NO_WARNINGS _AFXDLL WIN32 _MBCS _WINDOWS 
CONFIG += warn_off 
